[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    fastled/FastLED @ ^3.7.0
    mathieucarbou/AsyncTCP @ ^3.3.1
    mathieucarbou/ESPAsyncWebServer @ ^3.3.12

board_build.filesystem = littlefs

monitor_speed = 115200
upload_speed = 921600
