[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    fastled/FastLED @ ^3.7.0
    mathieucarbou/AsyncTCP @ ^3.3.1
    mathieucarbou/ESPAsyncWebServer @ ^3.3.12

board_build.filesystem = littlefs

monitor_speed = 115200
upload_speed = 921600
